name: BetterKingdoms
version: 'ALPHA'
main: dev.isnow.betterkingdoms.BetterKingdoms
api-version: '1.20'
author: '5170'
description: Kingdoms Plugin
website: https://github.com/TypicalModMaker/BetterKingdoms
load: POSTWORLD
softdepend:
  - PlaceholderAPI
libraries:
  - io.ebean:ebean:14.1.0
  - io.ebean:ebean-ddl-generator:14.1.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - com.h2database:h2:2.2.224
  - com.mysql:mysql-connector-j:8.3.0
  - de.exlll:configlib-paper:4.5.0